name: CI Test
on: [push]

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          distribution: 'adopt'
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: converter-${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: dev-install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: cov
        run: make cov
  build:
    name: "Docker build"
    runs-on: ubuntu-18.04
    needs: run_tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          distribution: 'adopt'
      - name: docker build
        run: make docker-build