name: Main Flow
on: [push, pull_request]

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: converter-${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: make dev-install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: cov
        run: make cov
  docker_build:
    name: "Docker build"
    runs-on: ubuntu-18.04
    needs: run_tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker build
        run: make docker-build
      - run: mkdir -p docker-cache && docker save -o docker-cache/converter.tar neto123/converter:latest
      - name: "Determine tag"
        if: "startsWith(github.ref, 'refs/tags/v')"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""
      - uses: actions/cache@v2
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          path: |
            docker-cache
          key: ${{ runner.os }}-docker-cache-${{ steps.determine-tag.outputs.tag }}
  docker_push:
    name: "Docker Push"
    needs:
      - run_tests
      - docker_build
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Determine tag"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""
      - uses: actions/cache@v2
        with:
          path: |
            docker-cache
          key: ${{ runner.os }}-docker-cache-${{ steps.determine-tag.outputs.tag }}
      - run: docker load < docker-cache/converter.tar
      - run: docker tag neto123/converter neto123/converter:${{ steps.determine-tag.outputs.tag }} && docker tag neto123/converter neto123/converter:latest
      - run: docker push neto123/converter:${{ steps.determine-tag.outputs.tag }} && docker push neto123/converter:latest